### ISSUE TITLE
Issues from 4/4/2016

### ISSUE THREAD

**Issue by DanielaGarza** [MD2Korg/mCerebrum#1]
Date: 4/4/2016
Issues from phone PF3

-	The system allows for an unlimited # of self-initiated smoking assessments and pays for all of them.
-	Paid the full amount for abandoned assessments..
-	Paid  for the full amount for missed assessments
-	The ringer is not loud enough.
-	For the “how many cigarettes” question, you need to click the “done” button in order to have access to the “next” button. This might be an issue as it’s not obvious that you have to click the done button.
-	2:39pm: I got a random assessment. In the middle of the assessment I got a notification that said “unfortunately autosense has stopped working”. What does this mean? Is there any action that should be taken?
-	Took off wrist bands at several points for a few hours. Was still showing “good data”. Still got paid full amount for assessments.
-	When at home kept getting “channel not available” pop up. What does this mean? What action should be taken?

**Comment by monowar** [comment]
issues resolved in new version
