### ISSUE TITLE
Restarting the Phone

### ISSUE THREAD

**Issue by DanielaGarza** [MD2Korg/mCerebrum#2]
Date: 4/6/2016
Time: 7:30 AM
Phone indicating that wrist sensors weren't picking up signals. Phone was restarted to try to resolve the issue. All Study Settings had been cleared and user had to reenter study settings on to phone. Start day button had been pressed before restarting phone and had to be pressed again after restarting the phone.

**Comment by twhnat** [comment]
This appears to be database related.  Please test in the latest version of the software.
