### ISSUE TITLE
Privacy not showing countdown

### ISSUE THREAD

**Issue by DanielaGarza** [MD2Korg/mCerebrum#3]
4/14/2016
10:00 AM
Phone 4 1003

Tried to show participant Privacy mode - no countdown was available on mCerebrum home screen even when Privacy mode starte

**Comment by twhnat** [comment]
@DanielaGarza Is this still a problem in the current version of software that you are running?

**Comment by DanielaGarza** [comment]
No, it seems to have been resolved. Thank you.
