### ISSUE TITLE
mCerebrum App Crashing

### ISSUE THREAD

**Issue by DanielaGarza** [MD2Korg/mCerebrum#4]
Date: 4/25/2016
Time: 4:41 PM 

I downloaded the new Rice test configuration and was pairing the devices to the phone. When I was done pairing the equipment to the phone the app started to crash. I force stopped the application but that did not fix the issue. I also restarted the phone which did not fix the issue either.

**Comment by twhnat** [comment]
@DanielaGarza Did resetting the database's fix this problem?

**Comment by DanielaGarza** [comment]
Yes, you fixed this issue when you called me to trouble shoot it!
