### ISSUE TITLE
End of Day

### ISSUE THREAD

**Issue by DanielaGarza** [MD2Korg/mCerebrum#5]
Date: 4/26/2016
Time: 8:11

Day started yesterday at 5:09 PM - I did not press end day button because it was not available at 10:00 PM when I went to bed. I assumed it would show me a start day button automatically after 12:00 AM but it did not. I just pressed End Day and will now have to wait the 4 hrs to see the start day button.

**Comment by twhnat** [comment]
@DanielaGarza This is the current expected behavior.  A future version will contain the new SOD/EOD implementation that will address this concern.
